package config

// agentDotsManagedPaths is the historical v14 migration snapshot of
// home-relative paths that Omni removes from dotfiles tracking. It is migration
// policy, not the live Agent Target catalog. ".agents" is intentionally narrowed
// to the skills store because other files directly under ".agents" are user-owned.
var agentDotsManagedPaths = []string{
	".aider-desk",
	".config/agents",
	".gemini/antigravity",
	".gemini/antigravity-cli",
	".astrbot/data",
	".autohand",
	".augment",
	".bob",
	".claude",
	".openclaw",
	".agents/skills",
	".codeartsdoer",
	".codebuddy",
	".codemaker",
	".codestudio",
	".codex",
	".commandcode",
	".continue",
	".snowflake/cortex",
	".config/crush",
	".cursor",
	".deepagents/agent",
	".config/devin",
	".factory",
	".firebender",
	".forge",
	".gemini",
	".copilot",
	".config/goose",
	".grok",
	".hermes",
	".inferencesh",
	".jazz",
	".junie",
	".iflow",
	".kilocode",
	".kiro",
	".kode",
	".lingma",
	".mcpjam",
	".vibe",
	".moxby",
	".mux",
	".config/opencode",
	".openhands",
	".ona",
	".pi/agent",
	".qoder",
	".qoder-cn",
	".qwen",
	".reasonix",
	".rovodev",
	".roo",
	".tabnine/agent",
	".terramind",
	".tinycloud",
	".trae",
	".trae-cn",
	".codeium/windsurf",
	".zencoder",
	".neovate",
	".pochi",
	".adal",
}
